### ISSUE TITLE
Normal Guardians do not spawn in Ocean monuments

### ISSUE THREAD

**Issue by smartwhatt** [PolyhedralDev/TerraDefaultConfig#34]
Monuments spawn with 3 elder guardians but normal guardians can not naturally spawn

**Comment by M3RGeo** [comment]
what terra version are you using fabric or bukkit (bukkit,spigot,paper) ?
I ask as Terra is unable to spawn guardians due to bukkit not exposing the API to make it possible to do that, so it isn't an issue with terra/ terra config packs, unless it's on fabric, I'm not sure if guardians spawn on the fabric implementation, but they probably do.

**Comment by solonovamax** [comment]
> Monuments spawn with 3 elder guardians but normal guardians can not naturally spawn

If you mean *re*spawning, then it is impossible to make them respawn. They can only be spawned when the structure is generated.

**Comment by mclegoman** [comment]
i have the same issue
also i run paper.

**Comment by Sancires** [comment]
Closing as this is known and is a limitation of Terra, not the default config.
